package com.alfredassistant.alfred_ai.ui

enum class AssistantState {
    IDLE,
    LISTENING,
    PROCESSING,
    SPEAKING,
    AWAITING_CONFIRMATION
}

/**
 * Represents a confirmation/options prompt generated by the AI.
 * Max 4 options, displayed above the orb.
 */
data class ConfirmationRequest(
    val prompt: String,
    val options: List<String>
)
