package com.alfredassistant.alfred_ai.ui

enum class AssistantState {
    IDLE,
    LISTENING,
    PROCESSING,
    SPEAKING,
    AWAITING_CONFIRMATION
}

/** Which visual interface to show */
enum class InterfaceMode {
    ORB,   // Classic Alfred orb animation
    WAVE   // Gemini-style glowing wave bar at bottom
}

/**
 * Represents a confirmation/options prompt generated by the AI.
 * Max 4 options, displayed above the orb/wave.
 */
data class ConfirmationRequest(
    val prompt: String,
    val options: List<String>
)
