package com.alfredassistant.alfred_ai.ui

enum class AssistantState {
    IDLE,
    LISTENING,
    PROCESSING,
    SPEAKING,
    AWAITING_CONFIRMATION,
    DISPLAYING_CARD
}

/**
 * Represents a confirmation/options prompt generated by the AI.
 * Max 4 options, displayed above the wave.
 */
data class ConfirmationRequest(
    val prompt: String,
    val options: List<String>,
    val buttonStyles: List<String> = emptyList(), // "primary", "secondary", or "cancel"
    /** Abbreviated version of prompt for TTS (phone numbers shortened, etc.) */
    val spokenPrompt: String = prompt
)
